"""add user table

Revision ID: 1fed8a2c9836
Revises: 77b32b3a8c31
Create Date: 2026-01-06 19:17:48.419547

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1fed8a2c9836"
down_revision: Union[str, Sequence[str], None] = "77b32b3a8c31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("status", sa.Boolean(), nullable=True))
    op.add_column("categories", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("categories", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("categories", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("products", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("products", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.add_column("products", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("products", sa.Column("status", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "status")
    op.drop_column("products", "updated_at")
    op.drop_column("products", "deleted_at")
    op.drop_column("products", "created_at")
    op.drop_column("categories", "updated_at")
    op.drop_column("categories", "deleted_at")
    op.drop_column("categories", "created_at")
    op.drop_column("categories", "status")
    # ### end Alembic commands ###
